stockManager/main/urls.py
from django.urls import path
from . import views

app_name = "main";
urlpatterns = [
    path("", views.index, name="index"),
    path("about/", views.about, name="about"),
];

stockManager/stockManager/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('main.urls')),
    path('stocks/', include('stocks.urls')),
    path('admin/', admin.site.urls),
]

stockManager/stocks/urls.py
from django.urls import path
from . import views

app_name = "stocks";
urlpatterns = [
    path("", views.index, name="stocks"),
    path("<int:id_stock>", views.stock, name="stock"),
    path("product/<int:id_product>", views.editProduct, name="product"),
];

stockManager/main/models.py
from django.db import models

# Create your models here.

stockManager/stocks/models.py
from django.db import models

class Product(models.Model):
    serialNumber = models.CharField(max_length=12);
    name = models.CharField(max_length=64);
    type = models.CharField(max_length=64);
    image = models.URLField();

    def __str__(self) -> str:
        return f"'{self.name}' ({self.type})";

##class Type(models.model):
### this table should include the type of products and the description to include in the Product

class Stock(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="products");
    quantity = models.PositiveIntegerField();

    def __str__(self) -> str:
        return f"{self.product} | {self.quantity}";

stockManager/main/views.py
from django import forms
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse
import openfoodfacts

from stocks.models import Product, Stock

class ReadBarcodeForm(forms.Form):
    barcode = forms.CharField(label="Barcode");

def index(request):
    if request.method == "POST":
        form = ReadBarcodeForm(request.POST);

        if form.is_valid():
            barcode = form.cleaned_data["barcode"];
            
            try:
                product = Product.objects.get(serialNumber=barcode);
            except Product.DoesNotExist:
                api = openfoodfacts.API(user_agent="MyAwesomeApp/1.0");
                response = api.product.get(barcode, fields=["code", "product_name", "image_front_url"]);

                if response == None:
                    p = Product.objects.create(
                        serialNumber=barcode,
                        name='missing',
                        type="default",
                        image="https://salonlfc.com/wp-content/uploads/2018/01/image-not-found-scaled-1150x647.png",
                    );
                    p.save();
                    s = Stock.objects.create(product=p, quantity=1);
                    s.save();
                    return redirect(f"stocks/product/{p.id}");
                else:
                    p = Product.objects.create(
                        serialNumber=barcode,
                        name=response['product_name'],
                        type="default",
                        image=response['image_front_url'],
                    );
                    p.save();
                    s = Stock.objects.create(product=p, quantity=1);
                    s.save();      
                    return redirect(f"stocks/{s.id}");         
            try:
                stock = Stock.objects.get(product=product);
                stock.quantity = stock.quantity + 1;
                stock.save();
            
                return redirect(f"stocks/{stock.id}");
            except (Stock.DoesNotExist):
                return render(request, "main/index.html", {
                    "form": ReadBarcodeForm()
                });
        else:
            return render(request, "main/index.html", {
                "form": form
            });
    return render(request, "main/index.html", {
        "form": ReadBarcodeForm()
    });

def about(request):
    return render(request, "main/about.html");

stockManager/stocks/views.py
from django import forms
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse
from stocks.models import Stock, Product

class StockForm(forms.Form):
    quantity = forms.IntegerField(label="Units");

class ProductForm(forms.Form):
    name = forms.CharField(label="Name");
    serialNumber = forms.CharField(label="Barcode");
    type = forms.CharField(label="Type");
    image = forms.URLField(label="Image");

def index(request):
    stocks = Stock.objects.all();
    return render(request, "stocks/index.html", {
        "stocks": stocks,
    });

def stock(request, id_stock):
    try:
        stock = Stock.objects.get(id=id_stock);
    except Stock.DoesNotExist:
        return HttpResponseRedirect(reverse("stocks:stocks"));
    
    if request.method == "POST":
        form = StockForm(request.POST);
    
        if form.is_valid():
           quantity =  form.cleaned_data["quantity"];
   
        stock.quantity = quantity;
        stock.save();
        
        return HttpResponseRedirect(reverse("stocks:stocks"));

    form = StockForm();
    form["quantity"].initial = stock.quantity;
    return render(request, "stocks/stock.html", {
        "stock": stock,
        "form": form,
    })

def editProduct(request, id_product):
    try:
        product = Product.objects.get(id=id_product);
        stock = Stock.objects.get(product=product);
    except Product.DoesNotExist or Stock.DoesNotExist:
        return HttpResponseRedirect(reverse("stocks:stocks"));

    if request.method == "POST":
        form = ProductForm(request.POST);
    
        if form.is_valid():
           name =  form.cleaned_data["name"];
           barcode =  form.cleaned_data["serialNumber"];
           type =  form.cleaned_data["type"];
           image = form.cleaned_data["image"];

           product.name = name;
           product.serialNumber = barcode;
           product.type = type;
           product.image = image;
           product.save();
            
           return HttpResponseRedirect(reverse("stocks:stock", kwargs={'id_stock': stock.id}));
    
    form = ProductForm();
    form["name"].initial = product.name;
    form["type"].initial = product.type;
    form["image"].initial = product.image;
    form["serialNumber"].initial = product.serialNumber;
    
    return render(request, "products/set.html", {
        "form": form,
        "product": product,
        "stock": stock,
    })

stockManager/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang='es'>
    <head>
        <title>Stock Manager</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <audio id="pip-sound" src="{% static 'pip-sound.wav' %}"></audio>
        <script src="https://unpkg.com/html5-qrcode" type="text/javascript"></script>
        {% load bootstrap5 %}
        {% bootstrap_css %}
        {% bootstrap_javascript %}
    </head>
<body>
    <nav class="navbar navbar-expand sticky-top navbar-dark bg-primary">
        <a class="navbar-brand" href="{% url 'main:index' %}">
            <img src="{% static 'barcode-scan.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
            Stock Manager
          </a>
        <div class="navbar-expand" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-item nav-link" href={% url 'main:index' %}>Barcode Scanner</span></a>
            <a class="nav-item nav-link" href={% url 'stocks:stocks' %}>Stock List</a>
            <a class="nav-item nav-link" href={% url 'main:about' %}>About</a>
          </div>
        </div>
      </nav>
    <div class="container-fluid">
        {% block body %}
        {% endblock %}
    </div>
</body>
</html>

stockManager/templates/main/about.html
{% extends "base.html" %}
{% block body %}
<h1>About</h1>
<p>Application created by <strong>Ezequiel Lamarque</strong></p>
<p>Email: <strong>ezequiel.lamarquee@gmail.com</strong></p>
<a target="_blank" href="https://www.github.com/ezelamar">Github</a>
{% endblock body %}

stockManager/templates/main/index.html
{% extends "base.html" %}
{% block body %}
<h1>Barcode Scanner</h1>
<p>Scan the Barcode of a product using the camera or complete the input by hand</p>
<div class="row">
  <div class="col-sm-12">
    <form id="barcode-form" action="{% url 'main:index' %}" method="post">
      {% csrf_token %}
      {{ form }}
      <input type="submit" value="Submit">
    </form>
  </div>
</div>
<br>
<div class="row">
  <div class="col-12" style="text-align: center;margin-bottom: 20px;">
    <div id="reader" style="max-width: 500px; min-height: 100px; text-align: center; position: relative; margin: auto;"></div>
  </div>
</div>
<script>
    function onScanSuccess(decodedText, decodedResult) {
        // handle the scanned code as you like, for example:
        console.log(`Code matched = ${decodedText}`, decodedResult);
        const barcode = document.getElementById("id_barcode");
        barcode.value = decodedText;
        const form = document.getElementById("barcode-form");
        document.body.style.background = "green";
        const pipSound = document.getElementById('pip-sound');
        pipSound.play();
        form.submit();
      }
      
      function onScanFailure(error) {
        //console.warn(`Code scan error = ${error}`);
      }
      
      let html5QrcodeScanner = new Html5QrcodeScanner(
        "reader",
        { fps: 10, qrbox: 250 },
        /* verbose= */ false);
      html5QrcodeScanner.render(onScanSuccess, onScanFailure);  
</script>
{% endblock body %}

stockManager/templates/products/set.html
{% extends "base.html" %}
{% block body %}
<h1>Update Product</h1>
<form action="{% url "stocks:product" product.id %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
  </form>
  <br>
<a class="btn btn-secondary" href="{% url "stocks:stock" stock.id %}">Back</a>
{% endblock body %}

stockManager/templates/stocks/index.html
{% extends "base.html" %}
{% block body %}
<h1>Stock List</h1>
<div class="container">
    <div class="row">
        <div class="col-sm-5">
            <ul class="list-group">
                {% for stock in stocks %}
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        <a href="{% url 'stocks:stock' stock.id %}"> {{ stock.product }}</a> 
                        <a href="{% url 'stocks:stock' stock.id %}" class="btn btn-success"> {{ stock.quantity }}</a>
                    </li>
                {% empty %}
                    <li>No Stocks.</li>
                {% endfor %}
            </ul>
        <div>
    </div>
    <br>
</div>
{% endblock body %}

stockManager/templates/stocks/stock.html
{% extends "base.html" %}

{% block body %}
<h1>Product Details</h1>
<div class="row">
    <div class="col-sm-6">
        <div class="card" style="width: 18rem;">
            <div class="card-header">
                Product
            </div>
            <img class="card-img-top" src={{ stock.product.image }} alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title">{{ stock.product.name }}</h5>
            </div>

                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        Barcode: {{ stock.product.serialNumber }}
                    </li>
                    <li class="list-group-item">
                        Type: {{ stock.product.type }}
                    </li>
                </ul>
                <div class="card-body">
                    <a href={% url 'stocks:product' stock.product.id %} class="btn btn-primary">Edit</a>
                </div>
        </div>
    </div>
    <div class="col-sm-6">
        <div class="card" style="width: 18rem;">
            <div class="card-header">
                Stock
            </div>
            <div class="card-body">
                <form action="{% url 'stocks:stock' stock.id %}" method="post">
                    {% csrf_token %}
                    {{ form }}
                    <input class="btn btn-outline-primary"type="submit" value="Update">
                </form>
            </div>
        </div>
    </div>
  </div>
  <br>
  <a class="btn btn-secondary"href="{% url 'stocks:stocks' %}">Back</a>
{% endblock %}